# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from concurrent import futures
import distributed_fs.distributed_fs_pb2 as distributed__fs__pb2
import distributed_fs.distributed_fs_pb2_grpc


class DistributedFileSystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadFile = channel.unary_unary(
            '/DistributedFileSystem/ReadFile',
            request_serializer=distributed__fs__pb2.ReadRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ReadResponse.FromString,
        )
        self.ListFiles = channel.unary_unary(
            '/DistributedFileSystem/ListFiles',
            request_serializer=distributed__fs__pb2.ListRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ListResponse.FromString,
        )
        self.UpdateFile = channel.unary_unary(
            '/DistributedFileSystem/UpdateFile',
            request_serializer=distributed__fs__pb2.UpdateRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.UpdateResponse.FromString,
        )
        self.GrantPermisions = channel.unary_unary(
            '/DistributedFileSystem/GrantPermisions',
            request_serializer=distributed__fs__pb2.PermissionRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.PermissionResponse.FromString,
        )
        self.CreateFile = channel.unary_unary(
            '/DistributedFileSystem/CreateFile',
            request_serializer=distributed__fs__pb2.CreateRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.CreateResponse.FromString,
        )
        self.DeleteFile = channel.unary_unary(
            '/DistributedFileSystem/DeleteFile',
            request_serializer=distributed__fs__pb2.DeleteRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.DeleteResponse.FromString,
        )


class DistributedFileSystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        # context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        # context.set_details('Method not implemented!')
        # raise NotImplementedError('Method not implemented!')
        print("Read Request Handled!")
        return distributed__fs__pb2.ReadResponse()

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantPermisions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributedFileSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ReadFile': grpc.unary_unary_rpc_method_handler(
            servicer.ReadFile,
            request_deserializer=distributed__fs__pb2.ReadRequest.FromString,
            response_serializer=distributed__fs__pb2.ReadResponse.SerializeToString,
        ),
        'ListFiles': grpc.unary_unary_rpc_method_handler(
            servicer.ListFiles,
            request_deserializer=distributed__fs__pb2.ListRequest.FromString,
            response_serializer=distributed__fs__pb2.ListResponse.SerializeToString,
        ),
        'UpdateFile': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateFile,
            request_deserializer=distributed__fs__pb2.UpdateRequest.FromString,
            response_serializer=distributed__fs__pb2.UpdateResponse.SerializeToString,
        ),
        'GrantPermisions': grpc.unary_unary_rpc_method_handler(
            servicer.GrantPermisions,
            request_deserializer=distributed__fs__pb2.PermissionRequest.FromString,
            response_serializer=distributed__fs__pb2.PermissionResponse.SerializeToString,
        ),
        'CreateFile': grpc.unary_unary_rpc_method_handler(
            servicer.CreateFile,
            request_deserializer=distributed__fs__pb2.CreateRequest.FromString,
            response_serializer=distributed__fs__pb2.CreateResponse.SerializeToString,
        ),
        'DeleteFile': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteFile,
            request_deserializer=distributed__fs__pb2.DeleteRequest.FromString,
            response_serializer=distributed__fs__pb2.DeleteResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'DistributedFileSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class DistributedFileSystem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadFile(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ReadFile',
                                             distributed__fs__pb2.ReadRequest.SerializeToString,
                                             distributed__fs__pb2.ReadResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFiles(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ListFiles',
                                             distributed__fs__pb2.ListRequest.SerializeToString,
                                             distributed__fs__pb2.ListResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFile(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/UpdateFile',
                                             distributed__fs__pb2.UpdateRequest.SerializeToString,
                                             distributed__fs__pb2.UpdateResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GrantPermisions(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/GrantPermisions',
                                             distributed__fs__pb2.PermissionRequest.SerializeToString,
                                             distributed__fs__pb2.PermissionResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateFile(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/CreateFile',
                                             distributed__fs__pb2.CreateRequest.SerializeToString,
                                             distributed__fs__pb2.CreateResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/DeleteFile',
                                             distributed__fs__pb2.DeleteRequest.SerializeToString,
                                             distributed__fs__pb2.DeleteResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
