# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import distributed_fs.distributed_fs_pb2 as distributed__fs__pb2


class DistributedFileSystemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFile = channel.unary_unary(
            '/DistributedFileSystem/CreateFile',
            request_serializer=distributed__fs__pb2.CreateRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.CreateResponse.FromString,
        )
        self.ListFiles = channel.unary_unary(
            '/DistributedFileSystem/ListFiles',
            request_serializer=distributed__fs__pb2.ListRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ListResponse.FromString,
        )
        self.ReadFile = channel.unary_unary(
            '/DistributedFileSystem/ReadFile',
            request_serializer=distributed__fs__pb2.ReadRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ReadResponse.FromString,
        )
        self.UpdateFile = channel.unary_unary(
            '/DistributedFileSystem/UpdateFile',
            request_serializer=distributed__fs__pb2.UpdateRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.UpdateResponse.FromString,
        )
        self.DeleteFile = channel.unary_unary(
            '/DistributedFileSystem/DeleteFile',
            request_serializer=distributed__fs__pb2.DeleteRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.DeleteResponse.FromString,
        )
        self.RestoreFile = channel.unary_unary(
            '/DistributedFileSystem/RestoreFile',
            request_serializer=distributed__fs__pb2.RestoreRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.RestoreResponse.FromString,
        )
        self.GrantPermissions = channel.unary_unary(
            '/DistributedFileSystem/GrantPermissions',
            request_serializer=distributed__fs__pb2.PermissionRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.PermissionResponse.FromString,
        )
        self.CreateNodeKeys = channel.unary_unary(
            '/DistributedFileSystem/CreateNodeKeys',
            request_serializer=distributed__fs__pb2.CreateNodeKeyRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.CreateNodeKeyResponse.FromString,
        )
        self.ReplicateFile = channel.unary_unary(
            '/DistributedFileSystem/ReplicateFile',
            request_serializer=distributed__fs__pb2.ReplicateFileRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ReplicateFileResponse.FromString,
        )
        self.ReplicateUpdateFile = channel.unary_unary(
            '/DistributedFileSystem/ReplicateUpdateFile',
            request_serializer=distributed__fs__pb2.ReplicateUpdateRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ReplicateUpdateResponse.FromString,
        )
        self.ReplicatePermissions = channel.unary_unary(
            '/DistributedFileSystem/ReplicatePermissions',
            request_serializer=distributed__fs__pb2.ReplicatePermissionRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ReplicatePermissionResponse.FromString,
        )
        self.ReplicateDeleteFile = channel.unary_unary(
            '/DistributedFileSystem/ReplicateDeleteFile',
            request_serializer=distributed__fs__pb2.ReplicateDeleteRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ReplicateDeleteResponse.FromString,
        )
        self.ReplicateRestore = channel.unary_unary(
            '/DistributedFileSystem/ReplicateRestore',
            request_serializer=distributed__fs__pb2.ReplicateRestoreRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.ReplicateRestoreResponse.FromString,
        )
        self.UpdateNodePublicKey = channel.unary_unary(
            '/DistributedFileSystem/UpdateNodePublicKey',
            request_serializer=distributed__fs__pb2.UpdateKeyRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.UpdateKeyResponse.FromString,
        )
        self.GetFileLock = channel.unary_unary(
            '/DistributedFileSystem/GetFileLock',
            request_serializer=distributed__fs__pb2.FileLockRequest.SerializeToString,
            response_deserializer=distributed__fs__pb2.FileLockResponse.FromString,
        )


class DistributedFileSystemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFile(self, request, context):
        """Client side functions

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantPermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNodeKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateFile(self, request, context):
        """Replication functions

        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateUpdateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicatePermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateDeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateRestore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNodePublicKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DistributedFileSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateFile': grpc.unary_unary_rpc_method_handler(
            servicer.CreateFile,
            request_deserializer=distributed__fs__pb2.CreateRequest.FromString,
            response_serializer=distributed__fs__pb2.CreateResponse.SerializeToString,
        ),
        'ListFiles': grpc.unary_unary_rpc_method_handler(
            servicer.ListFiles,
            request_deserializer=distributed__fs__pb2.ListRequest.FromString,
            response_serializer=distributed__fs__pb2.ListResponse.SerializeToString,
        ),
        'ReadFile': grpc.unary_unary_rpc_method_handler(
            servicer.ReadFile,
            request_deserializer=distributed__fs__pb2.ReadRequest.FromString,
            response_serializer=distributed__fs__pb2.ReadResponse.SerializeToString,
        ),
        'UpdateFile': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateFile,
            request_deserializer=distributed__fs__pb2.UpdateRequest.FromString,
            response_serializer=distributed__fs__pb2.UpdateResponse.SerializeToString,
        ),
        'DeleteFile': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteFile,
            request_deserializer=distributed__fs__pb2.DeleteRequest.FromString,
            response_serializer=distributed__fs__pb2.DeleteResponse.SerializeToString,
        ),
        'RestoreFile': grpc.unary_unary_rpc_method_handler(
            servicer.RestoreFile,
            request_deserializer=distributed__fs__pb2.RestoreRequest.FromString,
            response_serializer=distributed__fs__pb2.RestoreResponse.SerializeToString,
        ),
        'GrantPermissions': grpc.unary_unary_rpc_method_handler(
            servicer.GrantPermissions,
            request_deserializer=distributed__fs__pb2.PermissionRequest.FromString,
            response_serializer=distributed__fs__pb2.PermissionResponse.SerializeToString,
        ),
        'CreateNodeKeys': grpc.unary_unary_rpc_method_handler(
            servicer.CreateNodeKeys,
            request_deserializer=distributed__fs__pb2.CreateNodeKeyRequest.FromString,
            response_serializer=distributed__fs__pb2.CreateNodeKeyResponse.SerializeToString,
        ),
        'ReplicateFile': grpc.unary_unary_rpc_method_handler(
            servicer.ReplicateFile,
            request_deserializer=distributed__fs__pb2.ReplicateFileRequest.FromString,
            response_serializer=distributed__fs__pb2.ReplicateFileResponse.SerializeToString,
        ),
        'ReplicateUpdateFile': grpc.unary_unary_rpc_method_handler(
            servicer.ReplicateUpdateFile,
            request_deserializer=distributed__fs__pb2.ReplicateUpdateRequest.FromString,
            response_serializer=distributed__fs__pb2.ReplicateUpdateResponse.SerializeToString,
        ),
        'ReplicatePermissions': grpc.unary_unary_rpc_method_handler(
            servicer.ReplicatePermissions,
            request_deserializer=distributed__fs__pb2.ReplicatePermissionRequest.FromString,
            response_serializer=distributed__fs__pb2.ReplicatePermissionResponse.SerializeToString,
        ),
        'ReplicateDeleteFile': grpc.unary_unary_rpc_method_handler(
            servicer.ReplicateDeleteFile,
            request_deserializer=distributed__fs__pb2.ReplicateDeleteRequest.FromString,
            response_serializer=distributed__fs__pb2.ReplicateDeleteResponse.SerializeToString,
        ),
        'ReplicateRestore': grpc.unary_unary_rpc_method_handler(
            servicer.ReplicateRestore,
            request_deserializer=distributed__fs__pb2.ReplicateRestoreRequest.FromString,
            response_serializer=distributed__fs__pb2.ReplicateRestoreResponse.SerializeToString,
        ),
        'UpdateNodePublicKey': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateNodePublicKey,
            request_deserializer=distributed__fs__pb2.UpdateKeyRequest.FromString,
            response_serializer=distributed__fs__pb2.UpdateKeyResponse.SerializeToString,
        ),
        'GetFileLock': grpc.unary_unary_rpc_method_handler(
            servicer.GetFileLock,
            request_deserializer=distributed__fs__pb2.FileLockRequest.FromString,
            response_serializer=distributed__fs__pb2.FileLockResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'DistributedFileSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class DistributedFileSystem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFile(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/CreateFile',
                                             distributed__fs__pb2.CreateRequest.SerializeToString,
                                             distributed__fs__pb2.CreateResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListFiles(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ListFiles',
                                             distributed__fs__pb2.ListRequest.SerializeToString,
                                             distributed__fs__pb2.ListResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadFile(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ReadFile',
                                             distributed__fs__pb2.ReadRequest.SerializeToString,
                                             distributed__fs__pb2.ReadResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateFile(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/UpdateFile',
                                             distributed__fs__pb2.UpdateRequest.SerializeToString,
                                             distributed__fs__pb2.UpdateResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/DeleteFile',
                                             distributed__fs__pb2.DeleteRequest.SerializeToString,
                                             distributed__fs__pb2.DeleteResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestoreFile(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/RestoreFile',
                                             distributed__fs__pb2.RestoreRequest.SerializeToString,
                                             distributed__fs__pb2.RestoreResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GrantPermissions(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/GrantPermissions',
                                             distributed__fs__pb2.PermissionRequest.SerializeToString,
                                             distributed__fs__pb2.PermissionResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateNodeKeys(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/CreateNodeKeys',
                                             distributed__fs__pb2.CreateNodeKeyRequest.SerializeToString,
                                             distributed__fs__pb2.CreateNodeKeyResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateFile(request,
                      target,
                      options=(),
                      channel_credentials=None,
                      call_credentials=None,
                      insecure=False,
                      compression=None,
                      wait_for_ready=None,
                      timeout=None,
                      metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ReplicateFile',
                                             distributed__fs__pb2.ReplicateFileRequest.SerializeToString,
                                             distributed__fs__pb2.ReplicateFileResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateUpdateFile(request,
                            target,
                            options=(),
                            channel_credentials=None,
                            call_credentials=None,
                            insecure=False,
                            compression=None,
                            wait_for_ready=None,
                            timeout=None,
                            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ReplicateUpdateFile',
                                             distributed__fs__pb2.ReplicateUpdateRequest.SerializeToString,
                                             distributed__fs__pb2.ReplicateUpdateResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicatePermissions(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ReplicatePermissions',
                                             distributed__fs__pb2.ReplicatePermissionRequest.SerializeToString,
                                             distributed__fs__pb2.ReplicatePermissionResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateDeleteFile(request,
                            target,
                            options=(),
                            channel_credentials=None,
                            call_credentials=None,
                            insecure=False,
                            compression=None,
                            wait_for_ready=None,
                            timeout=None,
                            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ReplicateDeleteFile',
                                             distributed__fs__pb2.ReplicateDeleteRequest.SerializeToString,
                                             distributed__fs__pb2.ReplicateDeleteResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicateRestore(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/ReplicateRestore',
                                             distributed__fs__pb2.ReplicateRestoreRequest.SerializeToString,
                                             distributed__fs__pb2.ReplicateRestoreResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateNodePublicKey(request,
                            target,
                            options=(),
                            channel_credentials=None,
                            call_credentials=None,
                            insecure=False,
                            compression=None,
                            wait_for_ready=None,
                            timeout=None,
                            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/UpdateNodePublicKey',
                                             distributed__fs__pb2.UpdateKeyRequest.SerializeToString,
                                             distributed__fs__pb2.UpdateKeyResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileLock(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DistributedFileSystem/GetFileLock',
                                             distributed__fs__pb2.FileLockRequest.SerializeToString,
                                             distributed__fs__pb2.FileLockResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
