name: clean_code
on: 
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
       - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Check Version
        run: python --version
      
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=79
      
      - name: Lint with Pylint
        run: |
          pylint src


